server:
  ip: 127.0.0.1
  port: 8889


zookeeper:
  ip: 127.0.0.1
  port: 2181
  address: '${zookeeper.ip}:${zookeeper.port}'
  namespace: router
  rootPath: /root


redis:
  ip: 127.0.0.1
  port: 6379
  pwd: redis123


mybatis:
  datasource:
    -
      group: 1
      username: postgres
      password: postgres
      url: jdbc:postgresql://127.0.0.1:5432/cosdb?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=UTC
      driver: org.postgresql.Driver
    -
      group: 2
      username: postgres
      password: postgres
      url: jdbc:postgresql://127.0.0.1:5432/postgres?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=UTC
      driver: org.postgresql.Driver

kafka:
  address: 127.0.0.1:9092
  groupId: group0
  offset: earliest
  topics: 127.0.0.1

















