server:
  ip: 10.16.84.36
  port: 8889


zookeeper:
  ip: 10.33.65.9
  port: 2181
  address: '${zookeeper.ip}:${zookeeper.port}'
  namespace: im
  rootPath: /root


redis:
  ip: 10.33.65.9
  port: 6379
  pwd: redis12345


mybatis:
  datasource:
    -
      group: 1
      username: postgres
      password: 123qaz!@#
      url: jdbc:postgresql://127.0.0.1:5432/cosdb?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=UTC
      driver: org.postgresql.Driver
    -
      group: 2
      username: postgres
      password: 123qaz!@#
      url: jdbc:postgresql://127.0.0.1:5432/postgres?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=UTC
      driver: org.postgresql.Driver

kafka:
  address: 10.33.65.9:9092
  groupId: group0
  offset: earliest
  topics: 127.0.0.1

















