server:
  ip: 10.16.84.36
  port: 9999


zookeeper:
  ip: 10.33.65.9
  port: 2181
  address: '${zookeeper.ip}:${zookeeper.port}'
  namespace: im
  rootPath: /root


redis:
  ip: 10.33.65.9
  port: 6379
  pwd: redis12345


kafka:
  address: '10.33.65.9:9092'
  groupId: group0
  offset: earliest
  topics: server-127.0.0.1-9999-1,server-127.0.0.1-9999-2









