server:
  ip: 127.0.0.1
  port: 9999


zookeeper:
  ip: 127.0.0.1
  port: 2181
  address: '${zookeeper.ip}:${zookeeper.port}'
  namespace: im
  rootPath: /root


redis:
  ip: 127.0.0.1
  port: 6379
  pwd: redis123


kafka:
  address: '127.0.0.1:9092'
  groupId: group0
  offset: earliest
  topics: server-127.0.0.1-9999-1,server-127.0.0.1-9999-2









