server:
  port: 444
  servlet:
    context-path: /gateway
    session:
      timeout: 30m

logging:
  config: classpath:logback.xml


zookeeper:
  ip: 10.33.65.9
  port: 2181
  address: '${zookeeper.ip}:${zookeeper.port}'
  namespace: im
  rootPath: /root
